version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  mongo: 
    image: mongo:latest
    command: mongod --port 27027
    environment:
      - MONGO_INITDB_DATABASE=analyzer
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./docker/dbinit/:/docker-entrypoint-initdb.d/:ro
      - mongo-data:/data/db
    ports:
      - 27027:27027
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_REQUEST_SIZE=5999999999999kb    
      - ME_CONFIG_MONGODB_SERVER=mongo    
      - ME_CONFIG_MONGODB_PORT=27027

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: unless-stopped
    volumes:
      - kibana-data:/usr/share/kibana/config 
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
  mongo-data:
    driver: local
  kibana-data:
    
  